ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odometry0: /wheel_odom
    odometry0_config: [true, true, false, false, false, true,
                       false, false, false, false, false, false,
                       false, false, false]

    imu0: /rs_node/camera1/imu
    imu0_config: [false, false, false, true, true, true,
                  false, false, false, false, false, false,
                  false, false, false]

    use_control: false

